// Package prompt builds the text sent to each agent.
//
// It is the single place prompt wording lives, for two reasons. The obvious
// one is that a prompt scattered through the code cannot be reviewed as a unit.
// The load-bearing one is versioning: changing a prompt silently invalidates
// every earlier benchmark, so each build carries a version, and the run record
// stores it. Without that you cannot tell a real improvement from a reworded
// instruction — the two look identical in the numbers.
//
// Every field that comes from the user or a file passes through sanitize before
// it lands in a template. That is enforced by construction here: the brief is
// rendered, cleaned, and fenced in one function, so no caller can assemble a
// prompt that skips it.
package prompt

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/alextodea/parallel-builders/internal/brief"
	"github.com/alextodea/parallel-builders/internal/sanitize"
)

// Version changes whenever any wording below changes. Bump it deliberately:
// benchmark rows carrying different versions are not comparable, and bench
// refuses to average across them.
const Version = "1"

// Set is one rendered prompt plus the bookkeeping a run record needs.
type Set struct {
	Text     string
	Version  string
	Redacted int // secrets removed from embedded content; a spike is worth noticing
}

// Spec asks the architect for tests and nothing else.
func Spec(b brief.Brief, testGlobs []string) Set {
	var s strings.Builder
	s.WriteString(`Write the test suite for the feature described below.

Write ONLY tests. No implementation, no stubs, no scaffolding.

Every test must prove observable behaviour through a real interface. A test
whose only evidence is the implementation restating its own source text,
tokens, or a snapshot proves nothing.

Every test must be deterministic: no wall-clock time, no network, no
randomness, no dependence on test order.

Each test must FAIL against the current code — you are specifying something
that does not exist yet. It is expected and correct for the package not to
compile until a builder implements the feature.

Mark each test with the criterion it satisfies, as a trailing comment:

    func TestSomething(t *testing.T) { // pb:C1

Every criterion must have at least one test, and every test must name a real
criterion.
`)
	fmt.Fprintf(&s, "\nTest files must match: %s\n\n", strings.Join(testGlobs, ", "))
	return finish(s.String(), b)
}

// Build asks a builder to satisfy the frozen tests.
func Build(b brief.Brief, testGlobs []string) Set {
	var s strings.Builder
	fmt.Fprintf(&s, `Make the existing tests pass.

You may NOT modify any file matching: %s
Those tests are the specification. If you believe one is wrong, stop and say
so in your output — do not edit it.

Prefer the smallest change that works. Do not add a dependency unless there is
no reasonable alternative. Work only inside this directory.

`, strings.Join(testGlobs, ", "))
	return finish(s.String(), b)
}

// Repair hands a builder its own diff back. Large input, small output — the
// whole point of a repair round rather than a fresh generation.
func Repair(b brief.Brief, diff string, failing []string, note string) Set {
	var s strings.Builder
	s.WriteString(`Your previous attempt did not pass. Produce the SMALLEST patch that fixes
the failures below. Do not rewrite working code, do not restructure, and do
not edit any test file.

`)
	if len(failing) > 0 {
		s.WriteString("FAILING:\n")
		for _, f := range failing {
			fmt.Fprintf(&s, "  %s\n", f)
		}
		s.WriteString("\n")
	}
	if note != "" {
		// The note is generated by pb, not user content, so it needs no
		// sanitising — but keep it to one line.
		fmt.Fprintf(&s, "NOTE: %s\n\n", firstLine(note))
	}

	base := finish(s.String(), b)

	if strings.TrimSpace(diff) != "" {
		// The diff is the builder's own output. It can still contain a
		// secret the builder copied from somewhere, so it is cleaned too.
		cleanDiff, n := sanitize.Clean(diff)
		base.Redacted += n
		base.Text += "\n" + sanitize.Fence("your diff", cleanDiff)
	}
	return base
}

// Escalate asks the architect to reconsider the spec after every builder
// failed the same way. It gets a summary, never full diffs or transcripts.
func Escalate(b brief.Brief, failing []string, sizes string) Set {
	var s strings.Builder
	s.WriteString(`Every independent attempt failed the same way, so the problem is more
likely the specification than the code.

Either identify the flaw in these tests, or cut this feature into a smaller
slice. Do NOT write implementation.

`)
	if len(failing) > 0 {
		fmt.Fprintf(&s, "All builders failed: %s\n", strings.Join(failing, ", "))
	}
	if sizes != "" {
		fmt.Fprintf(&s, "Attempt sizes: %s\n", sizes)
	}
	s.WriteString("\n")
	return finish(s.String(), b)
}

// finish appends the sanitised, fenced brief and stamps the version. Every
// public builder ends here, so the sanitisation cannot be bypassed.
func finish(instructions string, b brief.Brief) Set {
	body, n := sanitize.Clean(b.Markdown())
	return Set{
		Text:     instructions + sanitize.Fence("brief", body),
		Version:  Version,
		Redacted: n,
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// Hash identifies the exact prompt, for the run record. Two runs with the same
// hash were given byte-identical instructions.
func Hash(sets ...Set) string {
	h := sha256.New()
	h.Write([]byte(Version + "\x00"))
	for _, s := range sets {
		h.Write([]byte(s.Text))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))[:12]
}
