package gate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func fixture(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("fixture %s: %v", name, err)
	}
	return string(b)
}

// These fixtures are real `go test -json` output, generated by running an
// actual toolchain — not hand-written approximations of it.
func TestGoParserOnRealOutput(t *testing.T) {
	t.Run("everything passes", func(t *testing.T) {
		r := GoParser{}.Parse(fixture(t, "pass.jsonl"), "", 0)

		if !r.OK() {
			t.Fatalf("expected OK, got %+v", r)
		}
		// TestOne and TestTwo/sub. TestTwo is a container, not a third test.
		if r.Passed != 2 || r.Total != 2 {
			t.Errorf("passed=%d total=%d, want 2/2 — a parent of a subtest must not be counted separately", r.Passed, r.Total)
		}
	})

	t.Run("failures, including a subtest", func(t *testing.T) {
		r := GoParser{}.Parse(fixture(t, "fail.jsonl"), "", 1)

		if r.Crashed {
			t.Error("ordinary test failures must not be reported as a crash")
		}
		want := []string{"TestOne", "TestTwo/beta"}
		if strings.Join(r.Failed, ",") != strings.Join(want, ",") {
			t.Errorf("Failed = %v, want %v — TestTwo is only failing because its subtest did", r.Failed, want)
		}
		if r.Passed != 1 {
			t.Errorf("Passed = %d, want 1 (TestTwo/alpha)", r.Passed)
		}
	})

	t.Run("build failure is a crash, not zero failures", func(t *testing.T) {
		// This is the case that would otherwise crown a broken candidate:
		// a package that will not compile produces no per-test results, so
		// counting FAIL lines yields zero failures.
		r := GoParser{}.Parse(fixture(t, "buildfail.jsonl"), "", 1)

		if !r.Crashed {
			t.Fatal("a non-compiling package must set Crashed")
		}
		if r.OK() {
			t.Fatal("a non-compiling package must never report OK")
		}
		if len(r.Failed) != 0 || r.Total != 0 {
			t.Errorf("a build failure has no test results: %+v", r)
		}
		if !strings.Contains(r.Note, "does not compile") {
			t.Errorf("Note should explain the crash, got %q", r.Note)
		}
	})

	t.Run("panic is a crash", func(t *testing.T) {
		r := GoParser{}.Parse(fixture(t, "panic.jsonl"), "", 1)

		if !r.Crashed {
			t.Fatal("a panicking suite must set Crashed — its results are incomplete by definition")
		}
		if r.OK() {
			t.Fatal("a panicking suite must never report OK")
		}
	})
}

func TestGoParserToleratesTruncatedOutput(t *testing.T) {
	// A killed suite cuts its last line mid-JSON. That must not fail the
	// parse, or a timeout becomes an unexplained error instead of a result.
	full := fixture(t, "fail.jsonl")
	cut := full[:len(full)-len(full)/3]

	r := GoParser{}.Parse(cut, "", 1)
	if len(r.Failed) == 0 && r.Total == 0 {
		t.Error("expected to salvage the complete lines before the cut")
	}
}

func TestGoParserCommandAddsJSON(t *testing.T) {
	cases := map[string]string{
		"go test ./...":            "go test -json ./...",
		"go test -race ./internal": "go test -json -race ./internal",
		"go test -json ./...":      "go test -json ./...", // already there
		"make test":                "make test",           // not a go command
	}
	for in, want := range cases {
		if got := (GoParser{}).Command(in); got != want {
			t.Errorf("Command(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestNoOutputAtAllIsACrash(t *testing.T) {
	r := GoParser{}.Parse("", "flag provided but not defined: -jsn\n", 2)
	if !r.Crashed {
		t.Fatal("a command that produced no events and exited non-zero is a crash, not a pass")
	}
	if !strings.Contains(r.Note, "no output") {
		t.Errorf("Note = %q", r.Note)
	}
}

func TestParserForFallsBackGracefully(t *testing.T) {
	if _, ok := ParserFor("go test ./..."); !ok {
		t.Error("go test should be recognised")
	}

	p, ok := ParserFor("pytest -q")
	if ok {
		t.Error("pytest is not implemented yet and should report so")
	}
	// The fallback must still gate correctly, it just cannot name tests.
	if r := p.Parse("", "", 0); !r.OK() {
		t.Error("exit 0 should pass under the fallback parser")
	}
	if r := p.Parse("", "", 1); r.OK() {
		t.Error("exit 1 should fail under the fallback parser")
	}
}

func TestClampKeepsHeadAndTail(t *testing.T) {
	if got, dropped := Clamp("short"); got != "short" || dropped != 0 {
		t.Errorf("short input should pass through untouched")
	}

	big := strings.Repeat("A", 10) + strings.Repeat("x", MaxOutput) + strings.Repeat("Z", 10)
	got, dropped := Clamp(big)

	if dropped == 0 {
		t.Fatal("expected truncation")
	}
	if !strings.HasPrefix(got, "AAAA") {
		t.Error("head lost — it carries the first failure")
	}
	if !strings.HasSuffix(got, "ZZZZ") {
		t.Error("tail lost — it carries the summary")
	}
	if !strings.Contains(got, "omitted") {
		t.Error("truncation must be visible, not silent")
	}
}
